apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/soniamarlo/pracFinal1-CICD.git
    targetRevision: main
    path: kubernetes/app 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
