version: 2.1

orbs:
  ggshield: gitguardian/ggshield@volatile
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  php-executor:
    docker:
      - image: circleci/php:8.0-cli
    working_directory: ~/repo
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

jobs:
  install_dependencies:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: |
            composer install --prefer-dist --no-interaction --no-scripts --no-progress
      - persist_to_workspace:
          root: ~/repo
          paths:
            - vendor

  run_tests:
    executor: php-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Copy .env File
          command: cp .env.example .env
      - run:
          name: Set Up Application Key
          command: php artisan key:generate
      - run:
          name: Run Database Migrations
          command: php artisan migrate --env=testing --database=sqlite
      - sonarcloud/scan
      - run:
          name: Run PHPUnit Tests
          command: |
            mkdir -p artifacts/test-results
            ./vendor/bin/phpunit --coverage-text --coverage-clover=artifacts/test-results/coverage.xml
      - store_artifacts:
          path: artifacts/test-results
          destination: test-results
          
  build_artifacts:
    executor: php-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Generate Application Archive
          command: |
            mkdir -p artifacts/package
            tar -czvf artifacts/package/release.tgz .
      - store_artifacts:
          path: artifacts/package/release.tgz
          destination: package/release.tgz

workflows:
  test-and-scan:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
          context: SonarCloud
      - ggshield/scan:
          name: security_scan
          base_revision: << pipeline.git.base_revision >>
          revision: << pipeline.git.revision >>
          requires:
            - run_tests
      - build_artifacts:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - main
