version: 2.1

orbs:
  ggshield: gitguardian/ggshield@volatile
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors:
  php-executor:
    docker:
      - image: circleci/php:8.0-cli
    working_directory: ~/repo
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

jobs:
  install_dependencies:
    executor: php-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Install Composer Dependencies
          command: |
            composer install --prefer-dist --no-interaction --no-scripts --no-progress
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: ~/repo
          paths:
            - vendor

  run_tests:
    executor: php-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Enable Xdebug
          command: |
            sudo docker-php-ext-enable xdebug
      - run:
          name: Copy .env File
          command: cp .env.example .env
      - run:
          name: Set Up Application Key
          command: php artisan key:generate
      - run:
          name: Run Database Migrations
          command: php artisan migrate --env=testing --database=sqlite
      - sonarcloud/scan
      - run:
          name: Run PHPUnit Tests with Coverage
          command: |
            mkdir -p ~/repo/artifacts/test-results
            XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text --coverage-clover=~/repo/artifacts/test-results/coverage.xml
      - run:
          name: Verify Artifacts Directory
          command: ls -la ~/repo/artifacts/test-results
      - store_artifacts:
          path: ~/repo/artifacts/test-results
          destination: test-results
      - store_test_results:
          path: ~/repo/artifacts/test-results

workflows:
  test-and-scan:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
          context: SonarCloud
      - ggshield/scan:
          name: security_scan
          base_revision: << pipeline.git.base_revision >>
          revision: << pipeline.git.revision >>
          requires:
            - run_tests
