version: 2.1

executors:
  php-executor:
    docker:
      - image: circleci/php:8.0-cli
    working_directory: ~/repo
    environment:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

jobs:
  install_dependencies:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: |
            composer install --prefer-dist --no-interaction --no-scripts --no-progress
      - persist_to_workspace:
          root: ~/repo
          paths:
            - vendor

  run_tests:
    executor: php-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Copy .env File
          command: cp .env.example .env
      - run:
          name: Set Up Application Key
          command: php artisan key:generate
      - run:
          name: Run Database Migrations
          command: php artisan migrate --env=testing --database=sqlite
      - run:
          name: Run PHPUnit Tests
          command: |
            mkdir -p artifacts/test-results
            ./vendor/bin/phpunit --coverage-text --coverage-clover=artifacts/test-results/coverage.xml
      - store_artifacts:
          path: artifacts/test-results
          destination: test-results

  security_scan:
    docker:
      - image: python:3.9  
    steps:
      - checkout
      - run:
          name: Install GitGuardian Shield
          command: pip install ggshield  
      - run:
          name: GitGuardian Security Scan
          command: ggshield secret scan repo .

workflows:
  version: 2
  test-and-scan:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
      - security_scan:
          requires:
            - run_tests
