apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: argocd-cicd
type: Opaque
stringData:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "ww2ROew2wRUqg4IiS4HpxtGGJWE5nhqcUtmoBgfd7sY="
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  MYSQL_ROOT_PASSWORD: "user"
  MYSQL_DATABASE: "laravel_in_kubernetes"
  MYSQL_PASSWORD: "user"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"



