apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: argocd-cicd
type: Opaque
stringData:
  APP_KEY: "ww2ROew2wRUqg4IiS4HpxtGGJWE5nhqcUtmoBgfd7sY="
  DB_HOST: "mysql-service"
  DB_DATABASE: "laravel_in_kubernetes"
  DB_USERNAME: "root"
  DB_PASSWORD: "user"



